/*/
File: QS_data_actions.sqf
Author:

	Quiksilver
	
Last modified:

	27/03/2018 A3 1.82 by Quiksilver
	
Description:

	Actions Text
___________________________________________/*/

[
    'Release',
	'Капітуляція',
	'Surrender',
	'Сидіти',
	'Стати',
	'Ескорт',
	'Загрузка',
	'Load',
	'Завантажте вантаж',
	'Вивантажити',
	'Розвантажте вантаж',
	'Питання цивільного',
	'Перетягнути',
	'Нести',
	'Слідувати',
	'Вербувати',
	'Положити',
	'Відмова',
	'Команда Відпустити',
	'Респаун транспорту',
	'Відкрити двері для вантажів',
	'Закрити двері для вантажів',
	'Service vehicle',
	'Clear vehicle inventory',
	'Unflip',
	'Оживити',
	'Арсенал',
	'Включити маячки',
	'Виключити маячки',
	'Буксирувати',
	'Rescue',
	'Порятунок',
	'Безпечний',
	'Turret safety',
	'Collect ear',
	'Collect gold tooth',
	'Вімкнути телевізор',
	'Вимкнути телевізор',
	'Активувати повітряну оборону',
	'Transport Leaderboard (Enable)',
	'Transport Leaderboard (Disable)',
	'Vote For Nighttime!',
	'Vote Against Nighttime!',
	'Unlock turret (Left)',
	'Unlock turret (Right)',
	'Lock turret (Left)',
	'Lock turret (Right)',
	'Cancel turret actions',
	'Приєднатись до групи',
	'Статус FOB',
	'Активувати FOB',
	'Активувати FOB респаун',
	'Cancel',
	'Unpack fortification',
	'Pack fortification',
	'Редагувати Інвентар',
	'Pick up intel','Підняти дані',
	'Drop intel','Кинути дані',
	'Upload intel',
	'Завантажити дані',
	'Activate device',
	'About Us',
	'Перевернути транспорт',
	'Включити телевізор',
	'Виключити телевізор',
	'Sit',
	'Stand',
	'Escort',
	'Load',
	'Load cargo',
	'Unload',
	'Unload cargo',
	'Question civilian',
	'Drag',
	'Carry',
	'Command Follow',
	'Command Recruit',
	'Command Dismiss',
	'Command Surrender',
	'Release',
	'Respawn vehicle',
	'Open cargo doors',
	'Close cargo doors',
	'Service vehicle',
	'Clear vehicle inventory',
	'Unflip',
	'Revive',
	'Arsenal',
	'Beacons On',
	'Beacons Off',
	'Tow',
	'Rescue',
	'Secure',
	'Turret safety',
	'Collect ear',
	'Collect gold tooth',
	'Turn on live feed',
	'Turn off live feed',
	'Activate air defense',
	'Transport Leaderboard (Enable)',
	'Transport Leaderboard (Disable)',
	'Vote For Nighttime!',
	'Vote Against Nighttime!',
	'Unlock turret (Left)',
	'Unlock turret (Right)',
	'Lock turret (Left)',
	'Lock turret (Right)',
	'Cancel turret actions',
	'Join group',
	'FOB Status',
	'Activate FOB',
	'Enable FOB Respawn',
	'Cancel',
	'Unpack fortification',
	'Pack fortification',
	'Edit Inventory',
	'Pick up intel',
	'Drop intel',
	'Upload intel',
	'Activate device',
	'About Us',
	'Push vehicle',
	'Скасувати',
	(localize 'STR_A3_BIS_fnc_initIntelObject_take'),
	'Забрати розвід данні',
	'Inflate boat',
	'Suspend side missions',
	'Resume side missions',
	'Suspend primary missions',
	'Resume primary missions',	
	'Cycle primary mission',
	'0 - Close Menu',
	'1 - (Target) Delete',
	'2 - Spectate',			
	'3 - Invincibility',
	'4 - Show Pilots',
	'5 - (Target) Repair',
	'6 - (Target) Pardon',
	'7 - (Target) Punish',
	'8 - Anti-hack (toggle)',
	'9 - Tag Map Markers',
	'10 - (Target) Revive',
	'11 - Map Teleport',
	'12 - (Clean) Base',
	'13 - (Clean) Island',
	'14 - Splendid Cam',
	'15 - Dev Terminal',
	'Швидкий спуск',
	'Fastrope AI units',
	'Відєднати швидку мотузку',
	'Включити швидкий спуск',
	'Відключити швидкий спуск',
	'Транспортний сервіс',
	'Pick up',
	'Download Locations',
	'Get Intel',
	'Treat at Medical Station',
	'Активувати транспорт',
	'Зброя на запобіжнику',
	'Spawn plane',
	'Підтвердіть ціль',
	'Звіт про ціль',
	'Raise plow',
	'Lower plow',
	'Розглянути',
	(localize 'STR_A3_action_useCatapult'),
	'Initiate Launch Sequence',
	'Launch',
	'Стабілізувати',
	'Inspect',
	'Self destruct',
	'Deploy camo net',
	'Remove camo net',
	'Mount slat armor',
	'Remove slat armor',
	'Retract Cargo Ropes',
	'Extend Cargo Ropes',
	'Shorten Cargo Ropes',
	'Release Cargo',
	'Deploy Cargo Ropes',
	'Attach To Cargo Ropes',
	'Drop Cargo Ropes',
	'Pickup Cargo Ropes',
	(if (isLocalized 'STR_A3_action_Recover_Boat') then {localize 'STR_A3_action_Recover_Boat'} else {'Recover boat'})
]