/*/
File: QS_data_actions.sqf
Author:

	Quiksilver
	
Last modified:

	27/03/2018 A3 1.82 by Quiksilver
	
Description:

	Actions Text
___________________________________________/*/

[
	'Sit',
	'Сидіти',
	'Stand',
	'Стати',
	'Escort',
	'Ескорт',
	'Load',
	'Загрузка',
	'Load cargo',
	'Завантажте вантаж',
	'Unload',
	'Вивантажити',
	'Unload cargo',
	'Розвантажте вантаж',
	'Question civilian',
	'Питання цивільного',
	'Drag',
	'Перетягнути',
	'Carry',
	'Нести',
	'Command Follow',
	'Слідувати',
	'Command Recruit',
	'Вербувати',
	'Command Dismiss',
	'Команда Відпустити',
	'Command Surrender',
	'Капітуляція',
	'Release',
	'Respawn vehicle',
	'Респаун транспорту',
	'Open cargo doors',
	'Відкрити двері для вантажів',
	'Close cargo doors',
	'Закрити двері для вантажів',
	'Service vehicle',
	'Clear vehicle inventory',
	'Unflip',
	'Revive',
	'Оживити',
	'Arsenal',
	'Арсенал',
	'Beacons On',
	'Включити маячки',
	'Beacons Off',
	'Виключити маячки',
	'Tow',
	'Буксирувати',
	'Rescue',
	'Secure',
	'Порятунок',
	'Turret safety',
	'Безпечний',
	'Collect ear',
	'Collect gold tooth',
	'Turn on live feed',
	'Вімкнути телевізор',
	'Включити телевізор',
	'Turn off live feed',
	'Вимкнути телевізор',
	'Виключити телевізор',
	'Activate air defense',
	'Активувати повітряну оборону',
	'Transport Leaderboard (Enable)',
	'Transport Leaderboard (Disable)',
	'Vote For Nighttime!',
	'Vote Against Nighttime!',
	'Unlock turret (Left)',
	'Unlock turret (Right)',
	'Lock turret (Left)',
	'Lock turret (Right)',
	'Cancel turret actions',
	'Join group',
	'Приєднатись до групи',
	'FOB Status',
	'Статус FOB',
	'Activate FOB',
	'Активувати FOB',
	'Enable FOB Respawn',
	'Активувати FOB респаун',
	'Cancel',
	'Unpack fortification',
	'Pack fortification',
	'Edit Inventory',
	'Редагувати Інвентар',
	'Pick up intel',
	'Підняти дані',
	'Drop intel',
	'Кинути дані',
	'Upload intel',
	'Завантажити дані',
	'Activate device',
	'About Us',
	'Push vehicle',
	'Перевернути транспорт',
	(localize 'STR_A3_BIS_fnc_initIntelObject_take'),
	'Take Intel',
	'Забрати розвід данні',
	'Inflate boat',
	'Suspend side missions',
	'Resume side missions',
	'Suspend primary missions',
	'Resume primary missions',	
	'Cycle primary mission',
	'0 - Close Menu',
	'1 - (Target) Delete',
	'2 - Spectate',			
	'3 - Invincibility',
	'4 - Show Pilots',
	'5 - (Target) Repair',
	'6 - (Target) Pardon',
	'7 - (Target) Punish',
	'8 - Anti-hack (toggle)',
	'9 - Tag Map Markers',
	'10 - (Target) Revive',
	'11 - Map Teleport',
	'12 - (Clean) Base',
	'13 - (Clean) Island',
	'14 - Splendid Cam',
	'15 - Dev Terminal',
	'Fastrope',
	'Швидкий спуск',
	'Fastrope AI units',
	'Detach fastrope',
	'Відєднати швидку мотузку',
	'Enable fastrope',
	'Включити швидкий спуск',
	'Disable fastrope',
	'Відключити швидкий спуск',
	'   ',
	'Pick up',
	'Download Locations',
	'Get Intel',
	'Treat at Medical Station',
	'Activate vehicle',
	'Активувати транспорт',
	'Weapons safe on base',
	'Зброя на запобіжнику',
	'Spawn plane',
	'Confirm target',
	'Підтвердіть ціль',
	'Report target',
	'Звіт про ціль',
	'Raise plow',
	'Lower plow',
	'Examine',
	'Розглянути',
	(localize 'STR_A3_action_useCatapult'),
	'Initiate Launch Sequence',
	'Launch',
	'Stabilise',
	'Стабілізувати',
	'Inspect',
	'Self destruct',
	'Deploy camo net',
	'Розгорнути маскувальну сітку',
	'Remove camo net',
	'Mount slat armor',
	'Remove slat armor',
	'Retract Cargo Ropes',
	'Extend Cargo Ropes',
	'Shorten Cargo Ropes',
	'Release Cargo',
	'Deploy Cargo Ropes',
	'Attach To Cargo Ropes',
	'Drop Cargo Ropes',
	'Pickup Cargo Ropes',
	'Положити',
	'Відмова',
	'Скасувати',
	'Транспортний сервіс',
	(if (isLocalized 'STR_A3_action_Recover_Boat') then {localize 'STR_A3_action_Recover_Boat'} else {'Recover boat'})
]
