/*/
File: QS_data_actions.sqf
Author:

	Quiksilver

Last modified:

	27/03/2018 A3 1.82 by Quiksilver

Description:

	Actions Text
___________________________________________/*/

[
	'Sit',
	'Сидіти',
	'Stand',
	'Стати',
	'Escort',
	'Супроводити',
	'Load',
	'Завантаження',
	'Load cargo',
	'Завантажити вантаж',
	'Unload',
	'Вивантажити',
	'Unload cargo',
	'Розвантажити вантаж',
	'Question civilian',
	'Допитати цивільного',
	'Drag',
	'Перетягти',
	'Carry',
	'Нести',
	'Command Follow',
	'Слідувати',
	'Command Recruit',
	'Вербувати',
	'Найняти',
	'Command Dismiss',
	'Команда Відпустити',
	'Command Surrender',
	'Капітуляція',
	'Release',
	'Відпустити',
	'Respawn vehicle',
	'Респаун транспорту',
	'Open cargo doors',
	'Відкрити двері для вантажів',
	'Close cargo doors',
	'Закрити двері для вантажів',
	'Service vehicle',
	'Обслуговування транспорту',
	'Clear vehicle inventory',
	'Очистити інвентар транспорту',
	'Unflip',
	'Перекинути',
	'Revive',
	'Оживити',
	'Arsenal',
	'Арсенал',
	'Beacons On',
	'Включити маячки',
	'Beacons Off',
	'Виключити маячки',
	'Tow',
	'Буксувати',
	'Rescue',
	'Врятувати',
	'Secure',
	'Розрядити',
	'Turret safety',
	'Безпека турелі',
	'Collect ear',
	'Забрати медальон',
	'Collect gold tooth',
	'Забрати золотий зуб',
	'Turn on live feed',
	'Увімкнути живу трансляцію',
	'Turn off live feed',
	'Вимкнути живу трансляцію',
	'Activate air defense',
	'Активувати повітряну оборону',
	'Transport Leaderboard (Enable)',
	'Transport Leaderboard (Disable)',
	'Vote For Nighttime!',
	'Vote Against Nighttime!',
	'Unlock turret (Left)',
	'Розблокувати турелі (Ліва)',
	'Unlock turret (Right)',
	'Розблокувати турелі (Права)'
	'Lock turret (Left)',
	'Заблокувати турелі (Ліва)'
	'Lock turret (Right)',
	'Заблокувати турелі (Права)'
	'Cancel turret actions',
	'Відмінити дії за турелями',
	'Join group',
	'Приєднатись до групи',
	'FOB Status',
	'Статус FOB',
	'Статус ПОБ',
	'Activate FOB',
	'Активувати FOB',
	'Активувати ПОБ',
	'Enable FOB Respawn',
	'Активувати FOB респаун',
	'Активувати ПОБ респаун',
	'Cancel',
	'Відмінити',
	'Unpack fortification',
	'Розпакувати укріплення',
	'Pack fortification',
	'Запакувати укріплення',
	'Edit Inventory',
	'Редагувати Інвентар',
	'Pick up intel',
	'Підняти дані',
	'Drop intel',
	'Кинути дані',
	'Upload intel',
	'Завантажити дані',
	'Activate device',
	'About Us',
	'Push vehicle',
	'Штовхнути транспорт',
	(localize 'STR_A3_BIS_fnc_initIntelObject_take'),
	'Take Intel',
	'Забрати данні',
	'Inflate boat',
	'Suspend side missions',
	'Resume side missions',
	'Suspend primary missions',
	'Resume primary missions',
	'Cycle primary mission',
	'0 - Close Menu',
	'1 - (Target) Delete',
	'2 - Spectate',
	'3 - Invincibility',
	'4 - Show Pilots',
	'5 - (Target) Repair',
	'6 - (Target) Pardon',
	'7 - (Target) Punish',
	'8 - Anti-hack (toggle)',
	'9 - Tag Map Markers',
	'10 - (Target) Revive',
	'11 - Map Teleport',
	'12 - (Clean) Base',
	'13 - (Clean) Island',
	'14 - Splendid Cam',
	'15 - Dev Terminal',
	'0 - Закрити меню',
	'1 - (Ціль) Видалити',
	'2 - Спостерігати',
	'3 - Непереможність',
	'4 - Показати пілотів',
	'5 - (Ціль) Відремонтувати',
	'6 - (Ціль) Вибачитись',
	'7 - (Ціль) Покарати',
	'10 - (Ціль) Оживити',
	'11 - Телепортація',
	'12 - (Очистити) Базу',
	'13 - (Очистити) Острів',
	'Fastrope',
	'Швидкий спуск',
	'Fastrope AI units',
	'Detach fastrope',
	'Відєднати мотузку',
	'Enable fastrope',
	'Увімкнути швидкий спуск',
	'Disable fastrope',
	'Вимкнути швидкий спуск',
	'   ',
	'Pick up',
	'Підняти',
	'Download Locations',
	'Get Intel',
	'Treat at Medical Station',
	'Activate vehicle',
	'Активувати транспорт',
	'Weapons safe on base',
	'Зброя на запобіжнику',
	'Spawn plane',
	'Confirm target',
	'Підтвердіть ціль',
	'Report target',
	'Звіт про ціль',
	'Raise plow',
	'Lower plow',
	'Examine',
	'Розглянути',
	(localize 'STR_A3_action_useCatapult'),
	'Initiate Launch Sequence',
	'Launch',
	'Stabilise',
	'Стабілізувати',
	'Inspect',
	'Self destruct',
	'Самознищення',
	'Deploy camo net',
	'Розгорнути маскувальну сітку',
	'Remove camo net',
	'Згорнути маскувальну сітку',
	'Mount slat armor',
	'Встановити зовнішню броню',
	'Remove slat armor',
	'Зняти зовнішню броню',
	'Retract Cargo Ropes',
	'Втягнути вантажні троси',
	'Extend Cargo Ropes',
	'Подовжити вантажні троси',
	'Shorten Cargo Ropes',
	'Вкоротити вантажні троси',
	'Release Cargo',
	'Відпустити вантажні троси',
	'Deploy Cargo Ropes',
	'Випустити вантажні троси',
	'Attach To Cargo Ropes',
	'Приєднати вантажні троси',
	'Drop Cargo Ropes',
	'Скинути вантажні троси',
	'Pickup Cargo Ropes',
	'Підняти вантажні троси',
	'Покласти',
	'Положити',
	'Відмова',
	'Скасувати',
	'Транспортний сервіс',
	(if (isLocalized 'STR_A3_action_Recover_Boat') then {localize 'STR_A3_action_Recover_Boat'} else {'Recover boat'})
]
